# Site settings
title: Course Website
subtitle: GSU Intro to Bioinformatics
description: |
  This is an introduction to bioinformatics
baseurl: "/GSU-intro-to-bioinformatics" # the subpath of your site, e.g. /blog/
url: "https://lskatz.github.com" # the base hostname & protocol for your site
syllabus: "/GSU-intro-to-bioinformatics/syllabus"
githubdir: "lskatz/GSU-intro-to-bioinformatics"

# Author/user information
email: lskatz@gmail.com
twitter_username: lskatz
github_username:  lskatz
authorurl: "https://lskatz.github.io"
address: |
  Atlanta, GA


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
